version: "3"

services:

  nginx:
    build: nginx
    restart: unless-stopped
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/default:/etc/nginx/sites-available/default
      - /etc/localtime:/etc/localtime:ro
      - ./logs/:/var/log/nginx/
    ports:
      - "80:80"
    environment:
      - TEST==mike
